## Libraries

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Conv2D
import numpy as np
from tensorflow.keras.preprocessing import image

 ## Training & DataLoader

In [ ]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
training_set = train_datagen.flow_from_directory('/content/drive/MyDrive/bio/archive/Cotton Disease/train',
                                                 target_size=  (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

# Preprocessing the Test set
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('/content/drive/MyDrive/bio/archive/Cotton Disease/test',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')

Found 1951 images belonging to 4 classes.
Found 106 images belonging to 4 classes.


## Building the CNN

In [ ]:
# Initialising the CNN
cnn = tf.keras.models.Sequential()

# Step 1 - Convolution
cnn.add(tf.keras.layers.Conv2D(filters=32,padding="same",kernel_size=3, activation='relu', input_shape=[64, 64, 3]))

# Step 2 - Pooling
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# Adding a second convolutional layer
cnn.add(tf.keras.layers.Conv2D(filters=32,padding='same',kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# Step 3 - Flattening
cnn.add(tf.keras.layers.Flatten())

# Step 4 - Full Connection
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

# Step 5 - Output Layer
cnn.add(tf.keras.layers.Dense(units=4, activation='softmax')) 

## Summary

In [ ]:
cnn.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 64, 64, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 32, 32, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 8192)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               1048704   
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 5

## Training the CNN

In [ ]:
# Compiling the CNN
cnn.compile(optimizer = 'adam',loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Training the CNN on the Training set and evaluating it on the Test set
cnn.fit(x = training_set, validation_data = test_set, epochs = 10)

Epoch 1/10
61/61 [==============================] - 1241s 20s/step - loss: 1.1403 - accuracy: 0.5274 - val_loss: 0.9767 - val_accuracy: 0.6132
Epoch 2/10
61/61 [==============================] - 22s 364ms/step - loss: 0.8069 - accuracy: 0.6966 - val_loss: 0.7426 - val_accuracy: 0.7075
Epoch 3/10
61/61 [==============================] - 22s 367ms/step - loss: 0.6703 - accuracy: 0.7376 - val_loss: 0.8411 - val_accuracy: 0.6038
Epoch 4/10
61/61 [==============================] - 23s 371ms/step - loss: 0.6208 - accuracy: 0.7519 - val_loss: 0.5306 - val_accuracy: 0.8019
Epoch 5/10
61/61 [==============================] - 22s 361ms/step - loss: 0.5243 - accuracy: 0.8063 - val_loss: 0.7080 - val_accuracy: 0.7075
Epoch 6/10
61/61 [==============================] - 22s 366ms/step - loss: 0.5182 - accuracy: 0.7960 - val_loss: 0.5188 - val_accuracy: 0.8019
Epoch 7/10
61/61 [==============================] - 22s 367ms/step - loss: 0.4492 - accuracy: 0.8273 - val_loss: 0.4944 - val_accuracy: 0.7925

## Testing 

In [ ]:
test_image = image.load_img('/content/drive/MyDrive/bio/archive/Cotton Disease/test/fresh cotton plant/dsd (153)_iaip.jpg',
                            target_size = (64,64))
test_image = image.img_to_array(test_image)
test_image=test_image/255
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)

In [ ]:
result

array([[0.00754536, 0.02967903, 0.0084659 , 0.95430976]], dtype=float32)

In [ ]:
result = result.ravel() 


In [ ]:
result


array([0.00754536, 0.02967903, 0.0084659 , 0.95430976], dtype=float32)

In [ ]:
n = len(result)
def largest(arr,n):
  
    # Initialize maximum element
    max = arr[0]
  
    # Traverse array elements from second
    # and compare every element with 
    # current max
    for i in range(1, n):
        if arr[i] > max:
            max = arr[i]
    return max
ans=largest(result,n)
print ("Largest in given array is",ans)


Largest in given array is 0.95430976


In [ ]:
result.sort

result 

array([0.00754536, 0.02967903, 0.0084659 , 0.95430976], dtype=float32)

In [ ]:
result=result.tolist() 

## Conclusion

In [ ]:
import numpy as np
result1=["diseased_leaf","diseased_plant","fresh_leaf","fresh_plant"]


In [ ]:

index = np.argmax(result)
print(index)
 
print("Largest element present in given array: " +str(ans)+" And it belongs to " +str(result1[index]) +" class.");      


3
Largest element present in given array: 0.95430976 And it belongs to fresh_plant class.
